name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm install

      - run: npx sst deploy --stage production
        env:
          AWS_ACCESS_KEY_ID: ${{ AKIA6QLQ7CEHY5EPHKXU }}
          AWS_SECRET_ACCESS_KEY: ${{ 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 }}
          AWS_DEFAULT_REGION: eu-central-1
          AWS_REGION: eu-central-1
